apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1

spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2

  template:
    metadata:
      labels:
        app: app2

    spec:
      containers:
        - name: c1
          image: rutugandhdocker1/website
          ports:
          - containerPort: 80
~                              